apiVersion: v1
kind: Service
metadata:
  name: lamp-ai
  labels:
    app: lamp-ai
spec:
  selector:
    app: lamp-ai
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
